COMMENT =	asciidoctor extension for various diagram types

DISTNAME =	asciidoctor-diagram-2.2.3

CATEGORIES =	textproc

HOMEPAGE =	https://github.com/asciidoctor/asciidoctor-diagram

# MIT
PERMIT_PACKAGE =	Yes

MODULES =		lang/ruby

CONFIGURE_STYLE =	ruby gem

.include <bsd.port.mk>
